### ISSUE TITLE
Diacritic problem with " ť " ("soften t)

### ISSUE THREAD

**Issue by neografia** [itfoundry/poppins#1]
Hi,
the soft t used in Slovak language is not available in Poppins font. The softening mark is below the letter t and it should be upper right. It is visible in the font table, I snapped it and attached so you may take a look. The gray letter shows how it should be and the black shows how it is.
I wonder if anyone can correct it somehow?
![t](https://cloud.githubusercontent.com/assets/12841589/8101853/59e0a838-101b-11e5-9b90-3f7adde62f8d.PNG)
ASCI Alt+156

**Comment by satyarajpurohit** [comment]
Hello,
Thanks for pointing this out. We'll get it fixed.

Best regards,
Satya

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Indian Type Foundry
Original, quality fonts for India and the Global World
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by neografia** [comment]
Great!
Thank you for your prompt replay!
Best regards,

Best regards,

Piotr Klasinski
Marketing Manager
[home-video-mail_2]<https://www.youtube.com/watch?v=Gw8o0LCH5Tk>
NEOGRAFIA
Sučianska 39A­
038-61 Martin-Priekopa, Slovakia
Mobil: +421 907 814 690
klasinski@neografia.sk<mailto:klasinski@neografia.sk>
www.neografia.sk<http://www.neografia.sk/>

**Comment by neografia** [comment]
Oh, just one more thing..or two:
– how long you predict it may take (approximetely)?
- will it be applied to Poppins light version also ?

Thank you and kind regards,
Piotr

**Comment by satyarajpurohit** [comment]
Hi Piotr,

We'll upload the new fonts to our Github account by Monday, however, I'm
not sure if you'll see them updated on on GoogleFonts anytime soon. They
generally take time to update.

Best, Satya

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Indian Type Foundry
Original, quality fonts for India and the Global World
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by neografia** [comment]
Thank you.
Is there any way to skip the Google Fonts updating time? Is it possible to get it stright from you?

Thank you and kind regards,
Piotr

**Comment by satyarajpurohit** [comment]
Yes, you should be able to download the latest updated fonts from our
Github account next week: https://github.com/itfoundry/poppins

Best, Satya

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Indian Type Foundry
Original, quality fonts for India and the Global World
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by neografia** [comment]
Grate!
Once again thank you for your prompt reaction!!!
Have a nice day!

**Comment by martinler** [comment]
Hello, 
we found same issue with "ť" character (t with caron) and unfortunately i don't see fix from 2015 year, latest changes are from 2014. Please, can you let me know where to get fixed font? Thanks 
Martin

**Comment by neografia** [comment]
I think it was fixed, try here: https://github.com/itfoundry/poppins

S pozdravom,
Piotr KLASINSKI
MARKETING MANAGER
[NEOGRAFIA]<https://youtu.be/o6WiQMkLBgU?autoplay=1>

mob.:   +421/907 814 690<tel:+421/907%20814%20690>
tel.:       +421/43/420 14 92<tel:+421/43/420%2014%2092>
e-mail:  klasinski@neografia.sk<mailto:klasinski@neografia.sk>
www.neografia.sk<http://www.neografia.sk/>
NEOGRAFIA, Sučianska 39A
038-61 Martin-Priekopa, Slovakia

**Comment by martinler** [comment]
Ahoj Piotr (albo cześć? :),

any version downloaded from github includes fonts from November 2014 and it still includes the bug. If you have on your computer correct version, i would be glad to get it from you, but i really can't see it here :(.

Martin
![screen shot 2016-05-13 at 13 08 01](https://cloud.githubusercontent.com/assets/19344005/15246314/30fbe860-190c-11e6-8d8b-f911321bda21.png)

**Comment by neografia** [comment]
Ahoj / Cześć,

I reported this bug in 2015, and got their answer that it’s fixed with a link I sent you before. However I never checked if and I do not have it;-/
Those guys however respond my emails promptly, so try to write ITF directly.

S pozdravom,
Piotr KLASINSKI
MARKETING MANAGER
[NEOGRAFIA]<https://youtu.be/o6WiQMkLBgU?autoplay=1>

mob.:   +421/907 814 690<tel:+421/907%20814%20690>
tel.:       +421/43/420 14 92<tel:+421/43/420%2014%2092>
e-mail:  klasinski@neografia.sk<mailto:klasinski@neografia.sk>
www.neografia.sk<http://www.neografia.sk/>
NEOGRAFIA, Sučianska 39A
038-61 Martin-Priekopa, Slovakia

**Comment by majlan** [comment]
It's still not working - both on Github and Google Fonts. Could you please solve this one? It's really making it impossible to use this font with certain languages...

**Comment by lianghai** [comment]
Fixed in the latest release 2.100: https://github.com/itfoundry/poppins/releases/tag/v2.100
